### ISSUE TITLE
FF at 15 min no longer works.

### ISSUE THREAD

**Issue by rhidan** [ng-m1nt/tft-farm-tokens-bot#1]
Riot has changed the FF button so I think the code needs to be updated in order to work again.

**Comment by ng-m1nt** [comment]
My life is getting busy right now. I will update it as soon as possible. 
Btw, the coordinates of FF button is laid on line 74. You can do research to correct the old coordinates.

**Comment by ng-m1nt** [comment]
The issue remains open until I update my script.

**Comment by cafefin** [comment]
@rhidan  my hot fix ,changed time surrender from 15mins to 10'30s 
https://github.com/cafefin/tft-farm-token

**Comment by ng-m1nt** [comment]
> @rhidan my hot fix ,changed time surrender from 15mins to 10'30s
> https://github.com/cafefin/tft-farm-token

Is your resolution 1920x1080?

**Comment by cafefin** [comment]
@ng-m1nt , No, its hardcode for 1280 x 720 Resolution

**Comment by ng-m1nt** [comment]
I fixed the problem.
