### ISSUE TITLE
Can't surrender anymore.

### ISSUE THREAD

**Issue by Silent-kun** [ng-m1nt/tft-farm-tokens-bot#2]
Pls update your code.

**Comment by ng-m1nt** [comment]
Thanks for your attention. My life is getting busy rn, so I will update the script as soon as possible.
The coordinates of FF button is laid on line 74 if you want to correct it yourself.

**Comment by cafefin** [comment]
@Silent-kun  my hot fix, change time surrender from 15mins to 10'30s 
https://github.com/cafefin/tft-farm-token
