### ISSUE TITLE
Add compiled version to `/releases`

### ISSUE THREAD

**Issue by LukeSavefrogs** [ng-m1nt/tft-farm-tokens-bot#6]
As said in #5 the Website has been taken down and it was the only way to download the compiled (`.exe`) version of your script.

Since i know how to use AutoIt so it's not a big problem for me to download it and compile from the Source Code... But it would be fantastic if you could add to the [releases page](https://github.com/ng-m1nt/tft-farm-tokens-bot/releases) the compiled version so that everybody can download it... 

The changes should reflect in the README too, if possible...

**Comment by ng-m1nt** [comment]
I'm not used to Github, I don't know how to add compiled file to release page. Instead, I made some changes in the README (●'◡'●)

**Comment by LukeSavefrogs** [comment]
> I'm not used to Github, I don't know how to add compiled file to release page. Instead, I made some changes in the README (●'◡'●)

**NICE UPDATE**! I really like the changes you made, including the explanation that was on the website and the link to Mega! 

Really good job!
Just remember to update the executables on MEGA if you change the script 😄
